class ServiceData {
  static List<String> availableServices = [
    'Preparation of NIC- one day service',
    'NIC - Initial',
    'NIC - Amendment',
    'NIC - Missing',
    'Submission of grievances',
    'Transportation of timber',
    'Transportation of animal',
    'Issuarance of income certificates/ asset certificates',
    'Issuarance of excise permits',
    'Registration of voluntary organizations',
    'Business name registration',
    'Obtain copies of business names taking',
    'Business name amendment',
    'Cancellation of business name',
    'Application for land kachcheri(regularization of unauthorized)',
    'Designation of post inheritance',
    'Grant of original rights(Grant)',
    'Lifetime registration',
    'Exclusion of manapatra lands',
    'Separation of schedules',
    'Processing of long term tax permits',
    'Transfer of land to departments',
    'Entry of schedules into the eslims systems',
    'Exemption to a leased land issuarance of a warrant',
    'Free directory setup(not available on lease)',
    'Wild elephant damage claim(property)',
    'Compensation for wild elephant damage(physical harm)',
    'Wild elephant damage compensation(life damage)',
    'Technical training programs',
    'Provision of food stamps',
    'Disability allowance',
    'Public assistance',
    'Sickness application',
    'Application for full disability benefits',
    'Senior allowance(above 70 years)',
    'Applying for twin benefits',
    'Applying for disabled equipment',
    'Application for family rehabilitation where mother/father/guardian died of kidney diseases'
  ];
}